version: "3.9"

services:
  parser:
    build: .
    volumes:
      - .:/app
    ports:
      - ${BACKEND_PORT}80:${BACKEND_PORT}
    environment:
      DEBUG: ${DEBUG}

      BACKEND_TTILE: ${BACKEND_TTILE}
      BACKEND_DESCRIPTION: ${BACKEND_DESCRIPTION}
      BACKEND_PREFIX: ${BACKEND_PREFIX}

      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_RELOAD: ${BACKEND_RELOAD}

      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}

      BACKEND_JWT_SECRET: ${BACKEND_JWT_SECRET}
      BACKEND_JWT_ALGORITHM: ${BACKEND_JWT_ALGORITHM}

      ENV: development
    networks:
      - default


  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 6gb
    volumes:
      - ./app/parser/data/:/tmp/data
    ports:
      - "4444:4444"
    environment:
      SE_NODE_OVERRIDE_MAX_SESSIONS: ${SE_NODE_OVERRIDE_MAX_SESSIONS}
      SE_NODE_MAX_SESSIONS: ${SE_NODE_MAX_SESSIONS}
